---

- name: Update the apt cache
  when: shared_drive_enabled|bool
  apt:
    update_cache: yes
    cache_valid_time: 7200

- name: Install NFS client package
  become: yes
  when: shared_drive_enabled|bool
  apt:
    name:
      - nfs-common
  tags:
    - nfs

- name: Check if /opt/data is already mounted
  debug: msg="The mount point exists"
  with_items: "{{ ansible_mounts }}"
  when: item.mount == "/opt/data"
  register: check_mount

- name: Create shared mount dir
  become: yes
  when: shared_drive_enabled|bool
  file:
    path: "{{ shared_mount_dir }}"
    owner: "{{ shared_dir_user }}"
    group: "{{ shared_dir_group }}"
    mode: "{{ shared_dir_mode|default(0775) }}"
    state: directory
  run_once: yes
  when: not check_mount
  tags:
    - nfs

- name: Mount directory in /etc/fstab
  become: yes
  when: shared_drive_enabled|bool
  mount:
    name: "{{ shared_mount_dir }}"
    src: "{{ shared_mount_address }}"
    opts: "{{ shared_mount_opts|default(omit) }}"
    fstype: nfs
    state: mounted
  tags:
    - nfs
