---
apache_mirror: archive.apache.org/dist
kafka_version: 3.2.3 
kafka_scala_version: "2.13"
kafka_download_sha512: sha512:09ec7a39d0e11494ede7d92cf7dfec5b95c6b0218e3b096b731d85ee8c442469e66aaf369a9c6750399719e515ee1bd372d609d6b232e3358e18aa2b57c90e29
kafka_user: kafka
kafka_group: kafka
kafka_data_dir: "{{ encrypted_root }}/kafka/data"
kafka_conf_dir: /etc/kafka/config
kafka_log_dir: /var/log/kafka
kafka_log_retention: 672 # 28 days
kafka_jmx_port: 9999
kafka_inter_broker_protocol_version: 3.2
kafka_log_message_format_version: 3.2
kafka_internal_topics: ["__consumer_offsets", "__transaction_state"]
