#!/bin/bash
echo "============================================================="
echo "=================checking disk health of HP server ==========="
echo "============================================================="
cchq echis run-shell-command hp_server --become "sudo smartctl -H /dev/sda | grep 'SMART Health Status'"
echo "==============================================================="
echo "=================checking disk health of baremetal=============="
echo "=============================================================="
cchq echis run-shell-command baremetal --become "sudo smartctl -H -d scsi /dev/sda | grep 'SMART Health Status'"
