deploy_env: production
env_monitoring_id: production
users:
  - dimagi
  - dimagi-support
  - g2
  - fissionlabs
slack_alerts_channel: alerts-production
secrets_backend: aws-secrets
slack_notifications_channel: C0B44C0Q2 # gtd-dev-support
