deploy_env: india
env_monitoring_id: india
users:
  - dimagi
  - fissionlabs
  - consultants
slack_alerts_channel: alerts-india
secrets_backend: aws-secrets
slack_notifications_channel: C0B44C0Q2 # gtd-dev-support
